[project]
name = "sent-bert"
version = "0.1.0"
description = "DistilBERT model fine tuned on IMDB movie reviews for enhanced sentiment analysis."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "jupyterlab>=4.4.3",
]
